apiVersion: v1
kind: Pod
metadata:
  name: pod-use-secret-as-mount
spec:
  containers:
  - name: secret-mount-pod
    image: nginx:alpine
    volumeMounts:
      - name: secret-volume
        mountPath: /etc/secrets
        readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret
