---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-indexhtml
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Custom Page</title>
    </head>
    <body style="background-color: lightblue;">
    <h1>Hello from ConfigMap!</h1>
    <p>Application version v1.0.0</p>
    <p>ConfigMap provides inline data for customization.</p>
    </body>
    </html>